### ISSUE TITLE
Can this be used to download the flac format?

### ISSUE THREAD

**Issue by CHJ85** [bplaat/albumdownloader#1]
Hi there. I tried changing the script to see if it would download in flac or mp3, none of which would work.
The m4a format is quite compressed and horrible sounding and sort of a last resort.
Is there any way this can be modified in order to download the lossless flac file, and if flac is not available fall back on mp3 320kbps?

**Comment by bplaat** [comment]
Hey CHJ85,

Thanks for trying out the script! I think it is not possible to download Youtube videos audio in the flac format. All audio streams are always compressed and I think that the artists / uploaders of the videos are also not uploading it in full CD-quality audio, so this was always not really possible.

I know that AAC streams don't have the best quality but for me it is good enough.
For example I always use a mid range Sony Bluetooth headset which uses Bluetooth so the audio is already encodes lossy in that protocol, so I don't can even hear a higher bandwidth audio codec 🤣.

But the script just uses youtube-dl / yt-dlp for the video downloading so you can try to add some more arguments to the command. But if Youtube it self is not giving you those audio streams it is not really possible sadly. But if you find out a way please let me know I'm also quite interested if it is possible somehow.

**Comment by CHJ85** [comment]
I see. I thought it downloaded from Deezer. But what you're saying is that it searches YouTube based on the metadata of the Deezer URL? I thought it was using Deezer's API. Sorry, my mistake.
But that explains the poor audio quality.

**Comment by bplaat** [comment]
Oh no the scripts uses the metadata from the Deezer API to search and download the right YouTube video, it is not possible to download music source files from Deezer it self
